// Code generated by Kitex v1.9.2. DO NOT EDIT.

package marketservice

import (
	"code.byted.org/kite/kitex/byted"
	"code.byted.org/kite/kitex/client"
	"code.byted.org/kite/kitex/client/callopt"
	"context"
	"github.com/cloudwego/kitex-examples/bizdemo/mall/business/mall_market/kitex_gen/cmp/ecom/market"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	AddCoupon(ctx context.Context, req *market.AddCouponReq, callOptions ...callopt.Option) (r *market.AddCouponResp, err error)
	GetCouponById(ctx context.Context, req *market.GetCouponByIdReq, callOptions ...callopt.Option) (r *market.GetCouponByIdResp, err error)
	UpdateCoupon(ctx context.Context, req *market.UpdateCouponReq, callOptions ...callopt.Option) (r *market.UpdateCouponResp, err error)
	DeleteCoupon(ctx context.Context, req *market.DeleteCouponReq, callOptions ...callopt.Option) (r *market.DeleteCouponResp, err error)
	UsingCoupon(ctx context.Context, req *market.UsingCouponReq, callOptions ...callopt.Option) (r *market.UsingCouponResp, err error)
	RetCoupon(ctx context.Context, req *market.RetCouponReq, callOptions ...callopt.Option) (r *market.RetCouponResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	config := byted.NewClientConfig()
	config.DestService = destService

	options = append(options, byted.ClientSuiteWithConfig(serviceInfo(), config))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kMarketServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kMarketServiceClient struct {
	*kClient
}

func (p *kMarketServiceClient) AddCoupon(ctx context.Context, req *market.AddCouponReq, callOptions ...callopt.Option) (r *market.AddCouponResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AddCoupon(ctx, req)
}

func (p *kMarketServiceClient) GetCouponById(ctx context.Context, req *market.GetCouponByIdReq, callOptions ...callopt.Option) (r *market.GetCouponByIdResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetCouponById(ctx, req)
}

func (p *kMarketServiceClient) UpdateCoupon(ctx context.Context, req *market.UpdateCouponReq, callOptions ...callopt.Option) (r *market.UpdateCouponResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateCoupon(ctx, req)
}

func (p *kMarketServiceClient) DeleteCoupon(ctx context.Context, req *market.DeleteCouponReq, callOptions ...callopt.Option) (r *market.DeleteCouponResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteCoupon(ctx, req)
}

func (p *kMarketServiceClient) UsingCoupon(ctx context.Context, req *market.UsingCouponReq, callOptions ...callopt.Option) (r *market.UsingCouponResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UsingCoupon(ctx, req)
}

func (p *kMarketServiceClient) RetCoupon(ctx context.Context, req *market.RetCouponReq, callOptions ...callopt.Option) (r *market.RetCouponResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RetCoupon(ctx, req)
}

// NewClientWithBytedConfig creates a client for the service defined in IDL.
func NewClientWithBytedConfig(destService string, config *byted.ClientConfig, opts ...client.Option) (Client, error) {
	if config == nil {
		config = byted.NewClientConfig()
	}
	config.DestService = destService

	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, byted.ClientSuiteWithConfig(serviceInfo(), config))
	options = append(options, opts...)
	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kMarketServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClientWithBytedConfig creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClientWithBytedConfig(destService string, config *byted.ClientConfig, opts ...client.Option) Client {
	kc, err := NewClientWithBytedConfig(destService, config, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}
